### ISSUE TITLE
在仅装了本Mod 1.2 版本 当放置 PanicleCraft (1.7.10-2.7.2) 的告示牌 (Advanced Sign) 时游戏会崩溃.

### ISSUE THREAD

**Issue by lktsuarpokqwq** [MayIHaveK/CustomEmoji#1]
在仅装了本Mod 1.2 版本 当放置 PanicleCraft (1.7.10-2.7.2) 的告示牌 (Advanced Sign) 时游戏会崩溃.
Forge: 10.13.4.1614
Optifine: E7

[错误报告-2024-5-13_15.13.23.zip](https://github.com/MayIHaveK/CustomEmoji/files/15290696/-2024-5-13_15.13.23.zip)

**Comment by MayIHaveK** [comment]
测试完毕，无高清修复的情况，放置PanicleCraft的告示牌的时游戏不会崩溃，存在高清修复的情况下会有此问题。

**Comment by MayIHaveK** [comment]
已修复该问题！
